### 회원 가입 (고객)
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
  "email": "chank2@naver.com",
  "name": "myName",
  "password": "pw",
  "birth": "1993-09-27",
  "phone": "01091319927"
}

### 이메일 인증 (고객)
GET http://localhost:8081/signup/customer/verify?email=chanki2@naver.com&code=

### 로그인 (고객)
POST http://localhost:8081/signin/customer
Content-Type: application/json

{
  "email": "chank2@naver.com",
  "password": "pw"
}

### 회원 정보 조회 (고객)
POST http://localhost:8081/customer/getInfo
Content-Type: application/json
X-AUTH-TOKEN:

### 잔액 변경 (고객)
POST http://localhost:8081/customer/balanace
Content-Type: application/json
X-AUTH-TOKEN:

{
  "from": "server",
  "message": "돈 충전",
  "money": 50000
}

################################

### 회원 가입 (셀러)

### 로그인 (셀러)